### PR TITLE
Python and WebDev project done

### PR DESCRIPTION
**Pull request by DanielMatiasCarvalho**
I believe I have accomplished all the requirements, if something is missing my apologies and please inform me, so I can correct it. 
In the python project, since I have some other tasks from other studys to do, I would like to focus on doing those, so I did not add much to the basic requirements, since I believe I already have a good basis in Python and coding in general.
In the WebDev, I decided in copying a website, since I have not had much practice in HTML and CSS, and it was a good opportunity to practice it.

### CODE REVIEW

**Comment by SrFrancisco** [comment]
Olá,
Antes de dar merge preciso de retirar os ficheiros do pycache (mas o projeto já se encontra entregue 🎉).

**Comment by DanielMatiasCarvalho** [comment]
Olá,
Queres que retire do pr eles?

**Comment by SrFrancisco** [comment]
Se consegues fazer já isso, pode ser. Assim já dou merge

**Comment by DanielMatiasCarvalho** [comment]
Francisco estou só com um problema, não tou a ver onde dar merge
[image: image.png]

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Sem
vírus.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em qua., 3 de jan. de 2024 às 14:51, Francisco ***@***.***>
escreveu:

**Comment by DanielMatiasCarvalho** [comment]
Francisco, estou só com um problema, não estou a ver como dar commit
novamente para o meu PR

[image: image.png]

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Sem
vírus.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em qua., 3 de jan. de 2024 às 14:51, Francisco ***@***.***>
escreveu:

**Comment by DanielMatiasCarvalho** [comment]
Okay, esquece, o meu Github é que não estava a atualizar, acredito que está
tudo certo?

Em qua., 3 de jan. de 2024 às 14:56, Daniel Carvalho <
***@***.***> escreveu:

**Comment by SrFrancisco** [comment]
Ok, está tudo em ordem 👍

**Pull request merged**
